# Generated by Django 6.0.3 on 2026-03-20 16:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('tables', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_type', models.CharField(blank=True, choices=[('flat', 'Flat (₹)'), ('percent', 'Percentage (%)')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('discount_reason', models.TextField(blank=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('split', 'Split Payment')], default='cash', max_length=20)),
                ('customer_count', models.IntegerField(default=1)),
                ('review_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('review_qr_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order')),
                ('receptionist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receptionist_invoices', to='workers.worker')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='restaurant.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tables.table')),
                ('waiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiter_invoices', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
