# Generated by Django 6.0.3 on 2026-03-20 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField(default=4)),
                ('zone', models.CharField(blank=True, help_text='e.g., Indoor, Outdoor, Terrace', max_length=100)),
                ('status', models.CharField(choices=[('free', 'Free'), ('occupied', 'Occupied'), ('awaiting_bill', 'Awaiting Bill'), ('cleaning', 'Cleaning'), ('reserved', 'Reserved')], default='free', max_length=20)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('qr_code_local', models.ImageField(blank=True, null=True, upload_to='tables/qrcodes/')),
                ('current_customers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('restaurant', 'number')},
            },
        ),
    ]
